
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/project-8f72949f-fe65-415a-a73/node-app/app', '.']

  # Push the container image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/project-8f72949f-fe65-415a-a73/node-app/app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'app-node', '--image', 'us-west1-docker.pkg.dev/project-8f72949f-fe65-415a-a73/node-app/app', '--region', 'us-west1', '--platform', 'managed', '--port', '3000', '--allow-unauthenticated']

images:
  - us-west1-docker.pkg.dev/project-8f72949f-fe65-415a-a73/node-app/app:latest
